export { ShareRegisterError } from "./errors.ts";
export {
  createOwnerOverview,
  type OwnerOverview,
  type OwnerOverviewRow,
} from "./owner-overview.ts";
export { createShareRegisterSnapshot, projectShareRegister } from "./projection.ts";
export {
  canonicalizeHoldings,
  countRanges,
  intersectRanges,
  normalizeRanges,
  rangesContain,
  rangesEqual,
  rangesOverlap,
  subtractRanges,
} from "./ranges.ts";
export {
  effectiveDateSchema,
  exactDecimalSchema,
  exactMoneySchema,
  exactPriceSchema,
  parseShareClass,
  parseShareholder,
  parseShareRegisterEvent,
  parseShareRegisterEvents,
  registeredAtSchema,
  shareClassSchema,
  shareholderDetailsSchema,
  shareholderSchema,
  shareRangeSchema,
  shareRegisterEventSchema,
} from "./schemas.ts";
export type {
  CancellationReason,
  EventMetadata,
  EventReversed,
  ExactDecimal,
  ExactMoney,
  ExactPrice,
  Holding,
  OpeningHolding,
  OpeningStateImported,
  RetiredRange,
  ShareCapitalChanged,
  ShareCapitalChangeReason,
  ShareClass,
  Shareholder,
  ShareholderDetails,
  ShareholderDetailsChanged,
  ShareRange,
  ShareRegisterDomainEvent,
  ShareRegisterEvent,
  ShareRegisterInput,
  ShareRegisterSnapshot,
  ShareRegisterState,
  SharesCancelled,
  SharesIssued,
  SharesRenumbered,
  SharesSplit,
  SharesTransferred,
  SourceActivityRecorded,
  TransferReason,
} from "./types.ts";
